#!/bin/bash
set -e

function copy_file() {
    rsync -a --no-perms $1 $HOME/dotfiles_backup/
    echo "copied $1 to $HOME/dotfiles_backup/$file"
}

function backup_file() {
    if [ -d $1 ]
    then
        cp -r $HOME/$1 $HOME/$1.bk
    else
        cp $HOME/$1 $HOME/$1.bk
    fi
    echo "Back up $HOME/$1.bk created"
}

cd "$(dirname "$0")/files"

for file in `ls -A`
do
  if [ -f $HOME/$file ] || [ -d $HOME/$file ]
  then
      read -p "$HOME/$file exist, overwrite it and created backup (y/n)? "

      if [[ $REPLY =~ ^[Yy]$ ]]
      then
          backup_file $file
          copy_file $file
      fi
  else
      copy_file $file
  fi
done
