#!/bin/bash

# dotfiles install script

# Copyright 2015 Basel Farah
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e
dotfiles_path=$( cd "$(dirname "$0")"/files && pwd )

function link_file() {
    ln -sf $dotfiles_path/$1 $HOME/$1
    echo "linked $1 to $HOME/$1"
}

function backup_file() {
    mkdir -p $HOME/dotfiles_backup

    rsync -a --no-perms $HOME/$1 $HOME/dotfiles_backup/$1.bk
    echo "Back up $HOME/$1.bk created"
}

cd $dotfiles_path

for file in `ls -A`
do
  if [ -f $HOME/$file ] || [ -d $HOME/$file ]
  then
      read -p "$HOME/$file exist, overwrite it and created backup (y/n)? "

      if [[ $REPLY =~ ^[Yy]$ ]]
      then
          backup_file $file
          link_file $file
      fi
  else
      link_file $file
  fi
done
