export PATH="$PATH:/usr/local/smlnj/bin"
export PS1="\033[01;32m\]\u\[\033[01;34m\]::\[\033[01;31m\]\h \[\033[00;34m\]{ \[\033[01;34m\]\w \[\033[00;34m\]}\[\033[01;32m\]-> \[\033[00m\]"

alias l="ls -altrG"
alias e="emacs"
alias v="vim -p"
alias start_server='python -m SimpleHTTPServer'
