export PATH="$PATH:/usr/local/smlnj/bin"

alias l="ls -altrG"
alias e="emacs"
alias v="vim -p"
alias start_server='python -m SimpleHTTPServer'

if [ -f $HOME/.secrets ]
then
  source $HOME/.secrets
fi

if [ -f $HOME/.a_git-completion.bash ]; then
  . $HOME/.a_git-completion.bash
fi

source $HOME/.rvm/scripts/rvm
